### ISSUE TITLE
Unneccessary Packages

### ISSUE THREAD

**Issue by D-Pagey** [andy-h1/Portfolio-Page#1]
Pretty sure you don't need `serve` or `yarn` in your project dependencies. These are normally global packages. So you should be able to `yarn remove serve yarn` and everything still work. 

https://github.com/andy-h1/Portfolio-Page/blob/f18832ccced6376f1fbe80ac4af55b04a3cffcde/package.json#L15

**Comment by andy-h1** [comment]
Thanks for this!
